# permissions for end users to edit srlinuxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: srlinux-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: srlinux-controller
    app.kubernetes.io/part-of: srlinux-controller
    app.kubernetes.io/managed-by: kustomize
  name: srlinux-editor-role
rules:
- apiGroups:
  - kne.srlinux.dev
  resources:
  - srlinuxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kne.srlinux.dev
  resources:
  - srlinuxes/status
  verbs:
  - get
