apiVersion: v1
kind: ConfigMap
metadata:
  name: srlinux-variants
data:
  ixrd1: |
    # ixrd1
    chassis_configuration:
      "chassis_type": 64
      "base_mac": 02:__RANDMAC__:00:00:00
      "cpm_card_type": 175

    slot_configuration:
      1:
        "card_type": 175
        "mda_type": 196

  ixrd2: |
    # ixrd2
    chassis_configuration:
      "chassis_type": 65
      "base_mac": 02:__RANDMAC__:00:00:00
      "cpm_card_type": 176

    slot_configuration:
      1:
        "card_type": 176
        "mda_type": 195

  ixrd3: |
    # ixrd3
    chassis_configuration:
      "chassis_type": 66
      "base_mac": 02:__RANDMAC__:00:00:00
      "cpm_card_type": 177

    slot_configuration:
      1:
        "card_type": 177
        "mda_type": 194

  ixr6: |
    # ixr6
    chassis_configuration:
      "chassis_type": 42
      "base_mac": 02:__RANDMAC__:00:00:00
      "cpm_card_type": 69

    slot_configuration:
      1:
        "card_type": 127
        "mda_type": 36

  ixr10: |
    # ixr10
    chassis_configuration:
      "chassis_type": 43
      "base_mac": 02:__RANDMAC__:00:00:00
      "cpm_card_type": 69

    slot_configuration:
      1:
        "card_type": 127
        "mda_type": 36
