---
name: CICD
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

env:
  GOVER: 1.17.2
  CGO_ENABLED: 0

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: kubebuilder tests
        run: make test

  staticcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

  golang-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=3m
          skip-go-installation: true
