# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
name: CICD
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

env:
  GOVER: 1.20.2
  CGO_ENABLED: 0

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: kubebuilder tests
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  golang-ci-lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config=./.github/workflows/linters/.golangci.yml
          version: "v1.51.2"
