# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

---
name: CICD
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

env:
  GOVER: 1.20.2
  CGO_ENABLED: 0

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: Test
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  golang-ci-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config=./.github/workflows/linters/.golangci.yml
          version: "v1.51.2"

  release:
    runs-on: ubuntu-22.04
    # start this job if a tag has been pushed
    # a tag is considered a release
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - golang-ci-lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVER }}

      - name: Build container
        run: "IMG=ghcr.io/srl-labs/srl-controller:$GITHUB_REF_NAME make docker-build"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push container
        run: "IMG=ghcr.io/srl-labs/srl-controller:$GITHUB_REF_NAME make docker-push"

      - name: Create GH release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
