# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

run:
  # running w/ 1.17 because we dont actually need/use 1.18 things and 1.18 breaks some linters.
  go: "1.17"
  timeout: 5m
  skip-dirs:
    - private
    - bin

output:
  sort-results: true

linters:
  enable:
    - nlreturn
    - forbidigo
    - gofumpt
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - prealloc
    - wsl

issues:
  # https://github.com/golangci/golangci-lint/issues/2439#issuecomment-1002912465
  # exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        # - gomnd
        # - dupl
        # - structcheck
        # - unused
        # - unparam
        - goerr113
        - gochecknoglobals
        - funlen
